config/routes.rb
Photo::Application.routes.draw do
  devise_for :users

  resources :directories

  get 'admin' => "admin#index"

	controller :sessions do
		get 'login' => :new
		post 'login' => :create 
		get 'logout' => :destroy
	end
	

  resources :images do
    member do
      post 'like_dislike'
    end
  end
	
	

  get "home/index"
	
	root :to => "home#index"
	

end

app/models/directory.rb
class Directory < ActiveRecord::Base
	has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :directory
	belongs_to :user

	has_attached_file :picture, :styles => {:medium => "300x300>", :thumb => "100x100>" }

	acts_as_votable

	validates :title, :description, :photographer, :presence => true
	
	validates_attachment_presence :picture



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
	has_many :images
	
	#has_secure_password

	acts_as_voter

  def admin?
    email == "bhushan.ahire@synechron.com"
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	#skip_before_filter :authorize
  def index
		@total_images = Image.count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :authenticate_user!
  	protect_from_forgery	
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  # GET /directories
  # GET /directories.json
  def index
    @directories = Directory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @directories }
    end
  end

  # GET /directories/1
  # GET /directories/1.json
  def show
    @directory = Directory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @directory }
    end
  end

  # GET /directories/new
  # GET /directories/new.json
  def new
    @directory = Directory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @directory }
    end
  end

  # GET /directories/1/edit
  def edit
    @directory = Directory.find(params[:id])
  end

  # POST /directories
  # POST /directories.json
  def create
    @directory = Directory.new(params[:directory])

    respond_to do |format|
      if @directory.save
        format.html { redirect_to @directory, notice: 'Directory was successfully created.' }
        format.json { render json: @directory, status: :created, location: @directory }
      else
        format.html { render action: "new" }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /directories/1
  # PUT /directories/1.json
  def update
    @directory = Directory.find(params[:id])

    respond_to do |format|
      if @directory.update_attributes(params[:directory])
        format.html { redirect_to @directory, notice: 'Directory was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directories/1
  # DELETE /directories/1.json
  def destroy
    @directory = Directory.find(params[:id])
    @directory.destroy

    respond_to do |format|
      format.html { redirect_to directories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.json
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/new
  # GET /images/new.json
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(params[:image])
		@image.directory_id = 1
    @image.user = current_user
    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.json
  def update
    @image = Image.find(params[:id])
    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :ok }
    end
  end

  def like_dislike
    @image = Image.find(params[:id])

    if params[:type] == "like"
      # @image.liked_by = current_user
      @image.vote :voter => current_user, :vote => 'like'
    else
      @image.downvote_from = current_user
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :authorize
  def new
  end

  def create
		user = User.find_by_name(params[:name])
		if user and user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to admin_url
		else
			redirect_to login_url, alert: "Invalid login"
		end
  end

  def destroy
		session[:user_id] = nil
		redirect_to login_url, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController	
  # GET /users
  # GET /users.json
	skip_before_filter :authorize
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User #{@user} was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: 'User #{@user} was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>

It's <%= Time.now %><br>
There are now <%= pluralize(@total_images, "image") %>

app/views/directories/_form.html.erb
<%= form_for(@directory) do |f| %>
  <% if @directory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory.errors.count, "error") %> prohibited this directory from being saved:</h2>

      <ul>
      <% @directory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directories/edit.html.erb
<h1>Editing contest</h1>

<%= render 'form' %>

<%= link_to 'Show', @directory %> |
<%= link_to 'Back', directories_path %>

app/views/directories/index.html.erb
<% @directories.each do |directory| %>
		<%= link_to directory.name, directory %><br>
		<% directory.images.each do |image| %>
			
			<div class="imagebox">
				<%= link_to image_tag(image.picture.url(:medium), :class => "image"), image.picture.url, :rel=>"prettyPhoto[pp_gal]", :title => image.title %>
				<div class="imagetext">
					<%= image.title %>
					<br>
					<%= image.description %>
					<br>
					<% if current_user.admin? %>	
						<%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete %><br/>
					<% end %>
					
					<div id="like_dislike_<%= image.id %>">
						<%= render :partial => "images/like_dislike", :locals => {:image => image} %>
					</div>

					<div class="exif" id="exif_<%=image.id%>" ><strong>Exif</strong>
						<div class="exifdata ">
							Cameramodel:
							<%= EXIFR::JPEG.new(image.picture.path).model rescue "N/A" %>
							<br>
							Date:
							<%= EXIFR::JPEG.new(image.picture.path).date_time rescue "N/A"  %>
							<br>
							Exposure:
							<%= EXIFR::JPEG.new(image.picture.path).exposure_time.to_s rescue "N/A"  %>
							<br>											
							Shutter:
							<%= EXIFR::JPEG.new(image.picture.path).shutter_speed_value.to_s rescue "N/A"%>
							<br>					
							Aperture:
							<%= EXIFR::JPEG.new(image.picture.path).aperture_value.to_s rescue "N/A"%>
						</div>
					</div>
				    
				</div>
			</div>





		<% end %>
		<% if current_user.admin? %>
			(
  		<%= link_to 'Edit', edit_directory_path(directory) %>
  		<%= link_to 'Destroy', directory, confirm: 'Are you sure?', method: :delete %>
			)	
		<% end %>
<% end %>

<br />
<% if current_user.admin? %>
	<%= link_to 'New Contest', new_directory_path %>
<% end %>

app/views/directories/new.html.erb
<h1>New contest</h1>

<%= render 'form' %>

<%= link_to 'Back', directories_path %>

app/views/directories/show.html.erb
<p>
  <b>Contest :</b>
  <%= @directory.name %>
</p>
	<% @directory.images.each do |image| %>
		<%= image.title %><br>	

		<div class="show">
			<a href="<%= image.picture.url %>" title=<%= image.title %> >
				<%= image_tag image.picture.url(:medium), :class => "image" %> 
			</a>
		</div>
	<% end %>

<% unless current_user.admin? %>
	<%= link_to 'Edit', edit_directory_path(@directory) %> |
	<%= link_to 'Back', directories_path %>
<% end %>

app/views/home/index.html.erb
<div class="details">
	<h3>Welcome <%= current_user.name %> to Synechron Photography Contest</h3>
        <dl>
          <dt>Entry Start: 01/10/2012</dd>
          <dt>Entry Close: 20/10/2012</dd>
        </dl><p>Are you an amateur photographer or a photography enthusiast? If so, then this is the competition for you!<strong>&nbsp;</strong></p>
<p>Submit your best shot clicked in year 2012. As a <strong>Member</strong>, you can <strong>enter only 1 photograph.</strong></p>
<p>Photographers of all ages, backgrounds and experience levels are invited to enter this competition where great imagery is everything, and creativity is the key ingredient!</p>

<p>Photographs taken by mobile not allowed.</p>
<p>Please make sure the image you upload should be min <strong>3264x2448</strong> resolution.</p>
<br/>

<p>
<h4>Rules</h4>
 <ul>
 	<li>You can upload only one photograph</li>
 	<li>Make sure your photo is up to the contest levels</li>
 	<li>Mobile photographs are not allowed</li>
 	<li>Min resolution of you image should be 3264x2448</li>
 	<li>You can like only one photograph</li>
 	<li>Vote the photo and not the photographer. Be the best judge. Be honest to yourself.</li>
 	<li>Winner will be announced with most likes.</li>
 </ul>
</p>

<p>
	<% if current_user %>              
	  <% unless current_user.images.length > 0 %><%= link_to "Enter contest", new_image_path  %><% end %>
	<% end %>
</p>

</div>

app/views/images/_form.html.erb
<%= form_for @image, :html => { :multipart => true }  do |f| %>
	
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :photographer %><br />
    <%= f.text_field :photographer %>
  </div>
	<%= hidden_field_tag :directory_id, 1 %>
	<%= f.file_field :picture %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/_like_dislike.html.erb
<% if current_user.voted_for? image %>
	<div style="height: 40px;"> <strong>Like : <%= image.likes.size %>,  Dislike : <%= image.dislikes.size %>,   Total : <%= image.votes.size %></strong></div>
<% else %>
<div class="btn-group" data-toggle="buttons-radio">
	<%= button_to "Like", {:action => "like_dislike", :id => image.id, :type => "like" }, :remote => true, :form => { "data-type" => "json" }, :class => "btn" %>
	<%= button_to "Dislike", {:action => "like_dislike", :id => image.id, :type => "dislike"}, :remote => true, :form => { "data-type" => "json" }, :class => "btn" %>
</div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<style type="text/css">
form {
	float: left;
    width: 60px;
}
</style>
<table>
<tr>
<% @images.each do |image| %>
<td>
		<div class="imagebox">
			<%= link_to image_tag(image.picture.url(:medium), :class => "image"), image.picture.url, :rel=>"prettyPhoto[pp_gal]", :title => image.title %>
			<div class="imagetext">
				<%= image.title %>
				<br>
				<%= image.description %>
				<br>
				<% if current_user.admin? %>	
					<%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete %><br/>
				<% end %>
				
				<div id="like_dislike_<%= image.id %>">
					<%= render :partial => "like_dislike", :locals => {:image => image} %>
				</div>
				<div style="clear:both"></div>
				<div class="exif" id="exif_<%=image.id%>" ><strong>Exif</strong>
					<div class="exifdata ">
						Cameramodel:
						<%= EXIFR::JPEG.new(image.picture.path).model rescue "N/A" %>
						<br>
						Date:
						<%= EXIFR::JPEG.new(image.picture.path).date_time rescue "N/A"  %>
						<br>
						Exposure:
						<%= EXIFR::JPEG.new(image.picture.path).exposure_time.to_s rescue "N/A"  %>
						<br>											
						Shutter:
						<%= EXIFR::JPEG.new(image.picture.path).shutter_speed_value.to_s rescue "N/A"%>
						<br>					
						Aperture:
						<%= EXIFR::JPEG.new(image.picture.path).aperture_value.to_s rescue "N/A"%>
					</div>
				</div>
			    
			</div>
		</div>

</td>
<% end %>
</tr>
</table>

<script type="text/javascript" charset="utf-8">

$(function() {
  // ...
  $("a[rel^='prettyPhoto']").prettyPhoto();
});


</script>

app/views/images/like_dislike.js.erb
$("#like_dislike_<%= @image.id %>").html("<%= escape_javascript(render(:partial => 'like_dislike', :locals => {:image => @image}))%>");

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<style type="text/css">
form {
	float: left;
    width: 60px;
}
</style>
<div class="show">
	<a href="<%= @image.picture.url %>" title=<%= @image.title %> >
		<%= image_tag @image.picture.url(:medium), :class => "image" %> 
	</a>
</div>
<div class="imagebox_show">
<p>
  <b>Title:</b>
  <%= @image.title %>
</p>

<p>
  <b>Filename:</b>
  <%= @image.picture_file_name %>
</p>

<p>
  <b>Description:</b>
  <%= @image.description %>
</p>

<p>
	<b>Photographer</b>
	<%= @image.photographer %>
</p>
<div id="like_dislike">
	<%= render :partial => "like_dislike", :locals => {:image => @image} %>
</div>
<div style="clear:both"></div>
<div class="exif" id="exif_<%=@image.id%>" ><strong>Exif</strong>
	<div class="exifdata ">
		Cameramodel:
		<%= EXIFR::JPEG.new(@image.picture.path).model rescue "N/A" %>
		<br>
		Date:
		<%= EXIFR::JPEG.new(@image.picture.path).date_time rescue "N/A"  %>
		<br>
		Exposure:
		<%= EXIFR::JPEG.new(@image.picture.path).exposure_time.to_s rescue "N/A"  %>
		<br>
		Width:
		<%= EXIFR::JPEG.new(@image.picture.path).width rescue "N/A" %>
		<br>
		Height:
		<%= EXIFR::JPEG.new(@image.picture.path).height rescue "N/A"  %>
		<br>					
		Shutter:
		<%= EXIFR::JPEG.new(@image.picture.path).shutter_speed_value.to_s rescue "N/A"%>
		<br>					
		Aperture:
		<%= EXIFR::JPEG.new(@image.picture.path).aperture_value.to_s rescue "N/A"%>
	</div>
</div>
<% if current_user.admin? %>
	<%= link_to 'Delete', image_path(@image), :confirm => "are you sure?", :method => :delete %> |
	<%= link_to 'Edit', edit_image_path(@image) %> |
	<%= link_to 'Back', images_path %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Photo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">          
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><a class="brand" href="<%= root_path %>">Home</a></li>
              <% if current_user %>
              <li><%= link_to "Photos", "/images"  %></li>
              <% unless current_user.images.length > 0 %><li><%= link_to "Upload Photo", new_image_path  %></li><% end %>
              <% end %>
              <li><% if current_user %><%= link_to "Sign out", destroy_user_session_path, :method => :delete %> <% else %> <%= link_to "Sign In", new_user_session_path %> <% end %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Synechron 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
  </body>
</html>